---
name: Dockerfile

on: [push]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    test:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Build image
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: Dockerfile
                  push: false

    push:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
